### ISSUE TITLE
why do we need this again

### ISSUE THREAD

**Issue by Abequinn** [OpenShopChannel/ShopChannel#1]
Copyright 2005-2014 Acer Cloud Technology, Inc. 
  All Rights Reserved.                         
 This software contains confidential information and    -->
  trade secrets of Acer Cloud Technology, Inc.           -->
  Use, disclosure or reproduction is prohibited without  -->
  the prior express written permission of Acer Cloud     -->
  Technology, Inc.

**Comment by spotlightishere** [comment]
I didn't realize anyone had committed the actual shop. I'll remove, thanks for pointing out.
