### ISSUE TITLE
please accept mee pull requesty!

### ISSUE THREAD

**Issue by lenlenlen345** [OpenShopChannel/ShopChannel#11]
I usedy power of otakuuuuuuuu to make the lill fucksy wucksy in code so fasty by using fanart of my cute little lenny len len! uwu owo uwo (づ｡ ◕‿‿◕｡)(づ｡ ◕‿‿◕｡)~(˘▾˘~)(｡◕‿◕｡)(▰˘◡˘▰)(▰˘◡˘▰)(>人<)(>人<)

**Comment by dhtdht020** [comment]
We have discord to share your favourite fan art (づ｡ ◕‿‿◕｡)

**Comment by lenlenlen345** [comment]
what's discordy? is it otaku fanarty sharing websitey???

**Comment by dhtdht020** [comment]
It's an otaku fanarty chatting service.
Move there. Invite can be found on the readme.
https://discord.gg/by6mR5N
