### ISSUE TITLE
Maintenance needed.

### ISSUE THREAD

**Issue by caution3** [OpenShopChannel/ShopChannel#12]
1. Most of the content in this repository is in `.php` format when no PHP content actually exists. We should probably change it to HTML for pages that won't use PHP.

And other corrections where the scripts may be redundant.

**Comment by InternalLoss** [comment]
Pages without the `<?` or `<?php` parts of the file wont be ran through PHP iirc (ie it wont parse and execute), so while semantically it may be annoying, it makes more sense unless we're removing extensions, because going to static.html from index.php would be highly annoying

**Comment by dhtdht020** [comment]
I'm almost certain we have discussed this already in the past when we changed from jsp, but as billy said it won't affect the actual files and only opens up the possibility of quickly adding PHP code to pages without the need to do a manual work of changing file paths on the entire repositiry or use IDEs / special tools to do that.

**Comment by caution3** [comment]
Understandable. 👍
