### ISSUE TITLE
A way to install a WAD/Homebrew App.

### ISSUE THREAD

**Issue by caution3** [OpenShopChannel/ShopChannel#17]
This is the second most important issue we need to resolve to date. We need to get SOAP working ASAP and start looking at getting homebrew to download over the OSC.

We should aim to be already doing this by late December.

- [ ] Analyze how WSC handles files from the server.
- [ ] Figure out encryption/decryption of files and tickets.
- [ ] Apply encryption to homebrew apps and test it over OSC.

**Dependencies**
- SOAP (for making a "purchase" of the app.)

**Resources**
- PHP
- JS
- Understanding of SSL

**Comment by caution3** [comment]
I'll be adding due dates to tasks from now on.

**Comment by WiiNoMa** [comment]
oh

**Comment by DarkPhoenix10** [comment]
yeah, we still haven't figured out how
but we're slowly getting there

**Comment by caution3** [comment]
The best way to get any of the tasks done is to analyze and break down the problem into steps, and then we can publish those steps so other users can reproduce them. :)
